name: kiteconnect_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  crypto: ^3.0.6
  http: ^1.5.0
  web_socket_channel: ^3.0.1
  meta: ^1.15.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
